server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: add_request_header_route
          uri: http://localhost:8080
          predicates:
            - Path=/get
          filters:
            - AddRequestHeader=X-Request-red, blue